### ISSUE TITLE
hey, just confused about the Boilerplate Code of Doc

### ISSUE THREAD

**Issue by Torres7707** [NoMoreDeps/ripple#1]
Hello, 

I just read the Update Externally chapter of the doc, and I have a question about the Boilerplate Code:
   
![image](https://github.com/NoMoreDeps/ripple/assets/44579340/5a1fdf89-f36c-436b-9c5c-509f5fb8a0c2)

as you can see from the screenshot, I am a little confused about the `get counter()`, cause you did not pass any Parameter to it, but when you use it inside of the `increment` func, you pass a Callback `_ => { _.count++ }`. This makes me confused.

I hope that you'll be able to help me figure it out.
thanks!

**Comment by NoMoreDeps** [comment]
Hi, Sorry for the long answer delay, I did not recived notification ((

In fact the updatecounter() will return the method you can use when you want to update a state outside a react component.
By default, you call the method with one parameter taht is the current state.

_ => { _.count++ } just manipulate the state variable  _;
If nothing is returned, you will at the end of the scope juste save all the changes.

**Comment by NoMoreDeps** [comment]
HI,

In fact updateCounter will return a method, that can be used in several ways : 

```ts
const update = updateCounter();

// Then you can update the state from inside the method by using a handler

// apply all pending modification to the ripple
// updateCounter(handler: (ripple) => void ) => void
updateCounter(ripple => {
  ripple.count++;
});

// cancel pending modifications
// update(handler: (ripple) => "restore") => void
update(ripple => "restore");

// reset the ripple to its initial state
// update(handler: (ripple) => "reset") => void
update(ripple => "reset");

// replace the ripple with a new value. Does not replace the initial state
// update(handler: (ripple) => typeof ripple) => void
update(ripple => {
  return {
    count: 0,
  };
});
```

So when the code do a this.counter it returns the method that can be used to update.
Why it use a method to get the method ?

Just because it create at the same time a proxy state dedicated to this call.
Without this, it may modify a shared state if you import twice into 2 components that try a update at the same time.

I will update the documentation to rename maybe variables to make it less confusing.
Thanks for the feedback, you are right it is ambigous.

To make it easier in the TodoService exemple I directly propose to get it that way  :

```ts
class TodoService {
  constructor(protected update = updateTasks()) { }
  ...
}
```
